### ISSUE TITLE
[Binary] in Nuget

### ISSUE THREAD

**Issue by hermanthotan** [dolphindb/api-csharp#4]
Do we have the dolphindb binary in nuget?
Can provide the link?

**Comment by dzhou284** [comment]
Herman，

Currently we don't deploy c# api binary in NuGet yet. If it is a quick work, will deploy there immediately!

**Comment by hermanthotan** [comment]
Thanks, as of Now i’m getting the binary dll from the unit test.

**Comment by windancer79** [comment]
Package is uploaded . 
https://www.nuget.org/packages/dolphindb_csharpapi/

**Comment by hermanthotan** [comment]
The binary is in .net framework.
I install it, it showing warning doesn't support .net core.
Maybe we need to fixed this in the next update

**Comment by windancer79** [comment]
Yes, the current binary is compiled on net framework 4.0 , We will release a binary based on .net core in the next update.
