### ISSUE TITLE
[Question] Additional Example

### ISSUE THREAD

**Issue by hermanthotan** [dolphindb/api-csharp#5]
Hi

I would like to request for additional sample 
1. We have records in the dfs data, how to perform delete 1 or many records in the database?
   in case the ts is not valid anymore or we want to reduce from 1 sec data into 1 mins data.
2. How to add dynamic partition, 
     db.run("db=database('dfs://testDatabase',VALUE,'MS' 'GOOG' 'FB' 'AMD')");
    a new symbol is adding into the system ex: NVIDIA, how to perform update the partition
3. How to perform append only records that is not in the database?
    it is can be done from the db.run(script) or need to handle from the C# code level

**Comment by xiaodanzhang** [comment]
Hi,

Thanks for trying DolphinDB.

1. DolphinDB does not support record level data deletion, but partition level. For example, if you use date as partition, you could drop partitions for certain days' data through function dropPartition.

2. if you use VALUE partition, it is recommended to add the following to your controller.cfg file.
newValuePartitionPolicy=add
The system will automatically add new partitions for you. The cluster or single node need to be restarted for this to take effect.

You could also add new partition on the fly through function addValuePartitions. Suppose you only have one level partition, you could use something like this:
db.run("addValuePartitions(db, ['NVIDIA'], 1)")

3. DolphinDB does not support conditional appending. But we will consider this feature in the future release. 

Best

DolphinDB Support
