### ISSUE TITLE
支持.net5/6/7吗

### ISSUE THREAD

**Issue by ZLVincent** [dolphindb/api-csharp#8]
支持.net5/6/7吗

**Comment by peeyee** [comment]
支持

**Comment by ZLVincent** [comment]
> 支持

![image](https://github.com/dolphindb/api-csharp/assets/8155380/ba01d079-c9fb-469e-bde4-24246bc960c5)

源码下载后这个Chart编译报错  麻烦问下需要安装什么package？

**Comment by peeyee** [comment]
提问请至discussions。
